// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: semantic.proto

package eu.trentorise.smartcampus.services.semantic.data.message;

public final class Semantic {
  private Semantic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string type = 1;
    boolean hasType();
    String getType();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // repeated .eu.trentorise.smartcampus.services.semantic.data.message.Tag tag = 4;
    java.util.List<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag> 
        getTagList();
    eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag getTag(int index);
    int getTagCount();
    java.util.List<? extends eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder> 
        getTagOrBuilderList();
    eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder getTagOrBuilder(
        int index);
    
    // repeated int64 relation = 5;
    java.util.List<java.lang.Long> getRelationList();
    int getRelationCount();
    long getRelation(int index);
  }
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(Builder builder) {
      super(builder);
    }
    private Data(boolean noInit) {}
    
    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }
    
    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .eu.trentorise.smartcampus.services.semantic.data.message.Tag tag = 4;
    public static final int TAG_FIELD_NUMBER = 4;
    private java.util.List<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag> tag_;
    public java.util.List<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag> getTagList() {
      return tag_;
    }
    public java.util.List<? extends eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder> 
        getTagOrBuilderList() {
      return tag_;
    }
    public int getTagCount() {
      return tag_.size();
    }
    public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag getTag(int index) {
      return tag_.get(index);
    }
    public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder getTagOrBuilder(
        int index) {
      return tag_.get(index);
    }
    
    // repeated int64 relation = 5;
    public static final int RELATION_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> relation_;
    public java.util.List<java.lang.Long>
        getRelationList() {
      return relation_;
    }
    public int getRelationCount() {
      return relation_.size();
    }
    public long getRelation(int index) {
      return relation_.get(index);
    }
    
    private void initFields() {
      type_ = "";
      name_ = "";
      description_ = "";
      tag_ = java.util.Collections.emptyList();
      relation_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getTagCount(); i++) {
        if (!getTag(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(4, tag_.get(i));
      }
      for (int i = 0; i < relation_.size(); i++) {
        output.writeInt64(5, relation_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, tag_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < relation_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(relation_.get(i));
        }
        size += dataSize;
        size += 1 * getRelationList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.semantic.data.message.Semantic.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          tagBuilder_.clear();
        }
        relation_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data build() {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data buildPartial() {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data result = new eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          relation_ = java.util.Collections.unmodifiableList(relation_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.relation_ = relation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data) {
          return mergeFrom((eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data other) {
        if (other == eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000008);
              tagBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        if (!other.relation_.isEmpty()) {
          if (relation_.isEmpty()) {
            relation_ = other.relation_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureRelationIsMutable();
            relation_.addAll(other.relation_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getTagCount(); i++) {
          if (!getTag(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder subBuilder = eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTag(subBuilder.buildPartial());
              break;
            }
            case 40: {
              ensureRelationIsMutable();
              relation_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addRelation(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string type = 1;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // repeated .eu.trentorise.smartcampus.services.semantic.data.message.Tag tag = 4;
      private java.util.List<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag> tag_ =
        java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          tag_ = new java.util.ArrayList<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag>(tag_);
          bitField0_ |= 0x00000008;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder> tagBuilder_;
      
      public java.util.List<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      public Builder setTag(
          int index, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTag(
          int index, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTag(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTag(
          int index, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTag(
          eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTag(
          int index, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTag(
          java.lang.Iterable<? extends eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          super.addAll(values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder getTagBuilder(
          int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder getTagOrBuilder(
          int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder> 
           getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
            eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.getDefaultInstance());
      }
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder addTagBuilder(
          int index) {
        return getTagFieldBuilder().addBuilder(
            index, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.getDefaultInstance());
      }
      public java.util.List<eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder> 
           getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder> 
          getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder, eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }
      
      // repeated int64 relation = 5;
      private java.util.List<java.lang.Long> relation_ = java.util.Collections.emptyList();;
      private void ensureRelationIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          relation_ = new java.util.ArrayList<java.lang.Long>(relation_);
          bitField0_ |= 0x00000010;
         }
      }
      public java.util.List<java.lang.Long>
          getRelationList() {
        return java.util.Collections.unmodifiableList(relation_);
      }
      public int getRelationCount() {
        return relation_.size();
      }
      public long getRelation(int index) {
        return relation_.get(index);
      }
      public Builder setRelation(
          int index, long value) {
        ensureRelationIsMutable();
        relation_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addRelation(long value) {
        ensureRelationIsMutable();
        relation_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllRelation(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureRelationIsMutable();
        super.addAll(values, relation_);
        onChanged();
        return this;
      }
      public Builder clearRelation() {
        relation_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.semantic.data.message.Data)
    }
    
    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.semantic.data.message.Data)
  }
  
  public interface TagOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // optional int64 id = 2;
    boolean hasId();
    long getId();
    
    // optional string description = 3;
    boolean hasDescription();
    String getDescription();
    
    // optional string summary = 4;
    boolean hasSummary();
    String getSummary();
  }
  public static final class Tag extends
      com.google.protobuf.GeneratedMessage
      implements TagOrBuilder {
    // Use Tag.newBuilder() to construct.
    private Tag(Builder builder) {
      super(builder);
    }
    private Tag(boolean noInit) {}
    
    private static final Tag defaultInstance;
    public static Tag getDefaultInstance() {
      return defaultInstance;
    }
    
    public Tag getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getId() {
      return id_;
    }
    
    // optional string description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string summary = 4;
    public static final int SUMMARY_FIELD_NUMBER = 4;
    private java.lang.Object summary_;
    public boolean hasSummary() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getSummary() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          summary_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      id_ = 0L;
      description_ = "";
      summary_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSummaryBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSummaryBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.semantic.data.message.Semantic.TagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        summary_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag build() {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag buildPartial() {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag result = new eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.summary_ = summary_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag) {
          return mergeFrom((eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag other) {
        if (other == eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasSummary()) {
          setSummary(other.getSummary());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              description_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              summary_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional int64 id = 2;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string description = 3;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
      }
      
      // optional string summary = 4;
      private java.lang.Object summary_ = "";
      public boolean hasSummary() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getSummary() {
        java.lang.Object ref = summary_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          summary_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSummary(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        summary_ = value;
        onChanged();
        return this;
      }
      public Builder clearSummary() {
        bitField0_ = (bitField0_ & ~0x00000008);
        summary_ = getDefaultInstance().getSummary();
        onChanged();
        return this;
      }
      void setSummary(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        summary_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.semantic.data.message.Tag)
    }
    
    static {
      defaultInstance = new Tag(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.semantic.data.message.Tag)
  }
  
  public interface ResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // required bool status = 2;
    boolean hasStatus();
    boolean getStatus();
  }
  public static final class Result extends
      com.google.protobuf.GeneratedMessage
      implements ResultOrBuilder {
    // Use Result.newBuilder() to construct.
    private Result(Builder builder) {
      super(builder);
    }
    private Result(boolean noInit) {}
    
    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }
    
    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // required bool status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private boolean status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getStatus() {
      return status_;
    }
    
    private void initFields() {
      id_ = 0L;
      status_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, status_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.services.semantic.data.message.Semantic.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result build() {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result buildPartial() {
        eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result result = new eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result) {
          return mergeFrom((eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result other) {
        if (other == eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // required bool status = 2;
      private boolean status_ ;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getStatus() {
        return status_;
      }
      public Builder setStatus(boolean value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.services.semantic.data.message.Result)
    }
    
    static {
      defaultInstance = new Result(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.services.semantic.data.message.Result)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016semantic.proto\0228eu.trentorise.smartcam" +
      "pus.services.semantic.data.message\"\225\001\n\004D" +
      "ata\022\014\n\004type\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\023\n\013descr" +
      "iption\030\003 \001(\t\022J\n\003tag\030\004 \003(\0132=.eu.trentoris" +
      "e.smartcampus.services.semantic.data.mes" +
      "sage.Tag\022\020\n\010relation\030\005 \003(\003\"E\n\003Tag\022\014\n\004nam" +
      "e\030\001 \002(\t\022\n\n\002id\030\002 \001(\003\022\023\n\013description\030\003 \001(\t" +
      "\022\017\n\007summary\030\004 \001(\t\"$\n\006Result\022\n\n\002id\030\001 \001(\003\022" +
      "\016\n\006status\030\002 \002(\010"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Data_descriptor,
              new java.lang.String[] { "Type", "Name", "Description", "Tag", "Relation", },
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data.class,
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Data.Builder.class);
          internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Tag_descriptor,
              new java.lang.String[] { "Name", "Id", "Description", "Summary", },
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.class,
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Tag.Builder.class);
          internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_services_semantic_data_message_Result_descriptor,
              new java.lang.String[] { "Id", "Status", },
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result.class,
              eu.trentorise.smartcampus.services.semantic.data.message.Semantic.Result.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
